### ISSUE TITLE
Bookmark

### ISSUE THREAD

**Issue by M-HARIS-97** [5-stones/react-native-readium#13]
Is readium support bookmark feature? if yes, How can I add?

**Comment by jspizziri** [comment]
@M-HARIS-97 my recommendation would be to build your own bookmarking outside of this library. Effectively you would build your own UI. You would locally track the current position via `onLocationChange`. Then when a user bookmarked a page you'd take the current location and store it somewhere.

Hopefully, that makes sense.

**Comment by M-HARIS-97** [comment]
OK. I'm planning to do it that way. Thanks for your comments.
