### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by M-HARIS-97** [5-stones/react-native-readium#15]
It works fine in debug mode. But, in the release build app crashes when navigating to ReadiumView page.

**Comment by jspizziri** [comment]
@M-HARIS-97 android? ios? or both?

If iOS make sure you're using the correct pod versions found in the README:

```
  pod 'GCDWebServer', podspec: 'https://raw.githubusercontent.com/readium/GCDWebServer/3ec154d358f26858071feaa6429e0f1c16bb11bd/GCDWebServer.podspec', modular_headers: true
  pod 'R2Shared', podspec: 'https://raw.githubusercontent.com/readium/swift-toolkit/2.4.0/Support/CocoaPods/ReadiumShared.podspec'
  pod 'R2Streamer', podspec: 'https://raw.githubusercontent.com/readium/swift-toolkit/2.4.0/Support/CocoaPods/ReadiumStreamer.podspec'
  pod 'R2Navigator', podspec: 'https://raw.githubusercontent.com/readium/swift-toolkit/2.4.0/Support/CocoaPods/ReadiumNavigator.podspec'
  pod 'Minizip', modular_headers: true
  ```
  
  As you need to use the fix that I implemented here https://github.com/readium/swift-toolkit/pull/76

**Comment by jspizziri** [comment]
@M-HARIS-97 I was just able to reproduce this in the example app. I'm going to take a deeper look today.

**Comment by jspizziri** [comment]
@M-HARIS-97 I have a solution for you. You need to add the following to your `AndroidManifest.xml`

```
<application
    ....
    android:usesCleartextTraffic="true"
    ....>
```

You can see [more detail here](https://stackoverflow.com/questions/52707918/webview-showing-err-cleartext-not-permitted-although-site-is-https). I'll add this to the `README.md` documentation for future users.

**Comment by jspizziri** [comment]
@M-HARIS-97 actually, I've found a much better way to do this that doesn't involve you updating anything on your end (I can actually add the config in the library itself). All you'll need to do is install the newest patch release [`1.0.2`](https://github.com/5-stones/react-native-readium/blob/main/CHANGELOG.md#102-2022-12-01).

**Comment by M-HARIS-97** [comment]
@jspizziri OK
