### ISSUE TITLE
Full screen causes problems on Android

### ISSUE THREAD

**Issue by M-HARIS-97** [5-stones/react-native-readium#22]
Readium full screen option works well on iOS. But it doesn't work well on Android.

In android :- Title and status bar part is not hidden in full screen option. Is there an option to enable / disable full screen? Also, how to handle the bottom page number indication? **(Page number hint doesn't work on Android)**

Please check the following screenshots;

**iOS**
![Simulator Screen Shot - iPhone 13 - 2022-12-15 at 11 30 29](https://user-images.githubusercontent.com/57429370/207785227-da8de1a7-7e21-4ea7-af77-f02736e3c2cf.png)

**android**
![image](https://user-images.githubusercontent.com/57429370/207785271-6298cef8-cec7-463d-8fe8-c0f88978fe8b.png)

**Comment by M-HARIS-97** [comment]
@jspizziri Under normal circumstances, it works fine. But if we use a navigation header on the reading page, it doesn't fill 100% of its parent.

**Comment by jspizziri** [comment]
@M-HARIS-97 that sounds like an artifact of how your navigation component works, not this library. If you can demonstrate otherwise via the example repo I'll re-open this issue.

**Comment by M-HARIS-97** [comment]
@jspizziri But it works fine on iOS. I use the same navigation header on iOS as well

**iOS with header** 
![Simulator Screen Shot - iPhone 13 - 2022-12-15 at 19 58 13](https://user-images.githubusercontent.com/57429370/207886422-39ffadd4-f92d-4d53-84cf-017b9ab79368.png)

**iOS without Header**
![Simulator Screen Shot - iPhone 13 - 2022-12-15 at 19 58 21](https://user-images.githubusercontent.com/57429370/207886503-e5e0acf5-92be-4b39-92a8-bb035f094fcf.png)


Anyway, I'll check out the example repo and update you

**Comment by jspizziri** [comment]
@M-HARIS-97 the navigation library itself could behave differently between those two platforms. That doesn't indicate an issue with this lib.

**Comment by M-HARIS-97** [comment]
@jspizziri Ok

**Comment by M-HARIS-97** [comment]
@jspizziri How to disable the full screen feature?

**Comment by jspizziri** [comment]
@M-HARIS-97 I'm not sure what you're asking. The view should simply be filling 100% of it's parent, so if you wrap it in a parent `View` of a certain size it should respect that.

**Comment by M-HARIS-97** [comment]
@jspizziri Got it ok. Ty :)

**Comment by M-HARIS-97** [comment]
@jspizziri Is there a way to prevent the fill 100%? Because i am using parent height value is **"device height - 100"** but when i click Readium view it fills device height automatically. I was able to reproduce this problem using the sample project. Steps;
1. Add height property (device height - 100)
2. Click on Readium view body part 
3. Then the Readium view height changes oddly

**Comment by jspizziri** [comment]
@M-HARIS-97 fork this project and create a repo in the example.

**Comment by andrebeolchi** [comment]
I'm having problems with fullscreen on android, to be honest I would like to remove it, is there any way to do this?
