### ISSUE TITLE
Is there any way to prevent users from copying text and screenshot the content ?

### ISSUE THREAD

**Issue by AmrithVengalath** [5-stones/react-native-readium#29]
I wish to know if this is any solution for preventing users from copying the text from the reader and taking screenshot.

**Comment by jspizziri** [comment]
It looks like there's a way in Readium to disallow copy however that would probably fall under [the LCP feature](https://github.com/5-stones/react-native-readium/issues/9). It doesn't look like preventing a screenshot is possible. Here are the rights restrictions that readium LCP supports https://readium.org/lcp-specs/releases/lcp/latest#36-identifying-rights-and-restrictions-the-rights-object

**Comment by jspizziri** [comment]
Incidentally, if you're interested in working on LCP support in this library please let me know!
