### ISSUE TITLE
Full screen causes problems on Android

### ISSUE THREAD

**Issue by andrebeolchi** [5-stones/react-native-readium#32]
I'm having problems with fullscreen on android, to be honest I would like to remove it, is there any way to do this?

The app's fullscreen on android does not remove the React Navigation Header, and besides, if I activate and deactivate the fullscreen a few times in a row, the location starts to "return" to the beginning of the chapter. I believe that removing the fullscreen action solves the location problem

_the fullscreen action I mean, is when you click in the middle of the screen_

[test.webm](https://github.com/5-stones/react-native-readium/assets/61586777/430646d8-7b17-4593-842a-6e5aafa92a5c)

**Comment by jspizziri** [comment]
@andrebeolchi I'm not entirely sure that the app should be responsible for removing your navigation header. I think disabling the native tap event would be best. What would potentially be even better would be to emit an event to the JS side if a tap did occur.

Open to a PR for this.

**Comment by amalStorilabs** [comment]
Have you solved this issue @andrebeolchi  ?
