### ISSUE TITLE
LCP support

### ISSUE THREAD

**Issue by katerynapeikova** [5-stones/react-native-readium#4]
Hi Jacob,
This package seems to be very promising! Wanted to have an updated on Readium LCP support. 

Can we expect it in any nearest future? How big/challenging is the scope of works seems to be?

Thanks in advance.

**Comment by jspizziri** [comment]
Hey @katerynapeikova ,

Sorry I missed the notification for this.

I don't think the LCP integration would be too challenging, it's just not a priority for the project we created this package for.

I'd be happy to provide oversight and guidance if you or anyone else would be interested in taking a crack at it.
