### ISSUE TITLE
XCode 15 Build error: Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by bilalshams7** [5-stones/react-native-readium#43]
Because of the dependency R2Streamer i can not run for IOS with XCode 15.

Swift Compiler Error (Xcode): /Users/coderythm/workspace/Digilib/bilal/wordrobe_mobile_app/ios/Pods/R2Streamer/Sources/Streamer/Server/PublicationServer.swift:364:6 Stored properties cannot be marked unavailable with '@available'

XCode version : 15.0
pods version : 1.12.1

**Comment by mickael-menu** [comment]
I just released Readium 2.6.0 which works on Xcode 15.

https://github.com/5-stones/react-native-readium/blob/1d3257e74a09ee6cbb34f7aab0ba522d19d67e34/example/ios/Podfile#L48-L49

**Comment by bilalshams7** [comment]
> I just released Readium 2.6.0 which works on Xcode 15.
> 
> https://github.com/5-stones/react-native-readium/blob/1d3257e74a09ee6cbb34f7aab0ba522d19d67e34/example/ios/Podfile#L48-L49

Worked for me. Thank you @mickael-menu for commenting

**Comment by jspizziri** [comment]
@bilalshams7 thanks for reporting. To close the loop on this, I've updated the documentation and example project to leverage the proper versions for Xcode 15 compliance.

Thanks @mickael-menu , as always!
