### ISSUE TITLE
[Feature Support] : To block apps like Google Reading Mode from accessing book content in our application.

### ISSUE THREAD

**Issue by bilalshams7** [5-stones/react-native-readium#45]
In my eBook application, measures are in place to restrict users from copying book content as a piracy prevention strategy. However, applications such as Google Reading Mode have activated accessibility features, allowing them to access our book content. Is there an approach to block accessibility features in the react-Native-readium package?

**Comment by mickael-menu** [comment]
Using [`FLAG_SECURE`](https://developer.android.com/reference/android/view/WindowManager.LayoutParams#FLAG_SECURE) on your Android window might help. That's in your app though, not in `react-native-readium`.

**Comment by jspizziri** [comment]
@bilalshams7 closing this as completed based on the above comment. LMK if you need anything else on this.
