### ISSUE TITLE
Project not working in IOS 

### ISSUE THREAD

**Issue by Mujab01** [5-stones/react-native-readium#46]
tried all . facing these error 
1.projectpath/ios/Pods/SwiftSoup/Sources/TokeniserState.swift:98:19 Protocol 'TokeniserStateProtocol' requires 'read' to be available in iOS 8.0 and newer

tried everything - clean build folder pod install 

any help appreciated 

Thanks.

**Comment by jspizziri** [comment]
You need to target iOS >= 13 as per the documentation.
