### ISSUE TITLE
[Bug]  ERROR  Warning: Function components cannot be given refs.

### ISSUE THREAD

**Issue by robert-elles** [5-stones/react-native-readium#52]
The error warning occurs when following the guide to build and run the example app [Example App] (https://github.com/5-stones/react-native-readium/blob/main/example/README.md). It is shown in Metro after the app starts (see screenshot). There is also a warning pop up in the app itself (see second screenshot).

![Screenshot 1 - Metro](https://github.com/5-stones/react-native-readium/assets/4633229/c04ae95a-8ca1-436a-9a1a-6c7864ec5a81)
![Screenshot 2 - App](https://github.com/5-stones/react-native-readium/assets/4633229/54bac372-c2a7-42eb-9036-8fbc90b88c07)

**Comment by jspizziri** [comment]
@robert-elles I've just merged [an upgrade to the latest stable version of react-native](https://github.com/5-stones/react-native-readium/pull/60). If you're still able, it'd be great to get your branched rebased on `main`. Then I'll pull it down and test it. If you're not able to rebase, I'll just have to fork your branch and do the rebase myself. LMK.

**Comment by jspizziri** [comment]
Fixed by https://github.com/5-stones/react-native-readium/pull/61
