### ISSUE TITLE
The package "react Native Readium" does not seems to linked 

### ISSUE THREAD

**Issue by AsifSabeer** [5-stones/react-native-readium#54]
The package "react Native Readium" does not seems to linked. We are using react Native version 0.74 which having auto-linking method. can you suggest how to link react native readium with ios. 

![simulator_screenshot_43082333-0D14-407C-BCF6-8FF978B38C41](https://github.com/5-stones/react-native-readium/assets/114659301/06f36c27-c1a5-4171-898d-e41da2d3a177)

**Comment by jspizziri** [comment]
I'm going to close this issue in favor of the one for upgrading to  newer versions of `react-native`.

https://github.com/5-stones/react-native-readium/issues/47
