### ISSUE TITLE
The 'react native readium' cannot be linked 

### ISSUE THREAD

**Issue by AsifSabeer** [5-stones/react-native-readium#55]
The 'react native readium' cannot be linked 
![simulator_screenshot_43082333-0D14-407C-BCF6-8FF978B38C41](https://github.com/5-stones/react-native-readium/assets/114659301/b1803310-f4ac-4948-a745-9009f10b6511)

**Comment by jspizziri** [comment]
What version of RN are you using and can you reproduce in the example app.

**Comment by jspizziri** [comment]
Closing due to lack of response.

**Comment by jm4r7in** [comment]
I have the same problem with expo and "react-native": "0.76.7"

**Comment by jspizziri** [comment]
@jm4r7in the first step would be to submit a reproduction. Also, I don't have a ton of knowledge around expo, so you might need to do most of the leg work with high level guidance from me.

**Comment by jm4r7in** [comment]
@jspizziri I'm sorry, I don't have much knowledge about expo either, and that's why I use it : it makes things easier.
Can't you just fix the error ?
`Java type mismatch expected (Mutable)Map<(raw) Any?, (raw) Any?>! but found HashMap<String, Any>. Use explicit cast`
I would appreciate it a lot.

**Comment by jspizziri** [comment]
@jm4r7in  we'll try to fix it eventually, when we have time. But given it's an issue we're encountering currently, we don't have a reproduction, and we don't use expo, it's probably boing to be quite a while before we get to it.

**Comment by jm4r7in** [comment]
@jspizziri it's ok, I don't need a fix, finally. I found an abandoned project that works.
