### ISSUE TITLE
Navigation header menu bar does not go off in Android

### ISSUE THREAD

**Issue by amalStorilabs** [5-stones/react-native-readium#56]
I am facing an issue in android were i am not able to show the ReadiumView content in full screen in android becuase the top menu bar stays on always. In iOS when the user taps the screen both system navigation and top menu will disappear in android this default behavoiur is not working . I was trying a workaround by toggling the headerShown option in navigation but inside the readiumView the usertaps are not detecting , is there any way to trigger the onPress method

The code :

<SafeAreaView style={[styles.container, { height: windowHeight }]}>
      <StatusBar hidden={true} />
      <ReadiumView
          style={{ flex: 1 }}
          file={{
            url: route.params.filePath,
            initialLocation: route.params.locationId,
          }}
          settings={settings}
          location={location}
          onLocationChange={(locator) => {
            locationChanged(locator);
          }}
          onTableOfContents={(toc) => {
            if (toc) {
              setToc(toc);
            }
          }}
        />
    </SafeAreaView>

React-Native Version : 0.68

**Comment by jspizziri** [comment]
@amalStorilabs , this issue has been reported a few other times. Please take a look at those issue threads. At the end of the day, I need you to submit a repro based the `example` project (so you'll do it based on a fork of this repo).

I'll reopen this issue if you're able to do that but I'm going to close it until then.
