### ISSUE TITLE
Android: Lag in Applying User Preferences When Reopening Reading Module

### ISSUE THREAD

**Issue by amalStorilabs** [5-stones/react-native-readium#62]
When we repeatedly open the reading module by going back and reopening it, there is a noticeable lag on Android when applying user preferences, such as font size and appearance. The settings initially display the default values before transitioning to the user-specified preferences. This issue is specific to Android, as iOS provides a visual indication with a loader until the page is fully rendered. I've verified that the settings variables are correctly set in the React Native code, so it appears to be an Android-specific issue.

**Comment by jspizziri** [comment]
@amalStorilabs, what version of the library are you using?

**Comment by jspizziri** [comment]
@amalStorilabs , please see my question above, also please document steps to reproduce this within the example project. If I don't hear back from you in a couple of days I'm going to close this issue.

**Comment by amalStorilabs** [comment]
Sorry for the delay in response . 

Steps to reproduce
1 . Open a book
2. Change the appearance/theme of the book
3. Click back to exit from book
4. Click again to enter the book
5. When 3 and 4 are repeated continously there is a lag in rendering the book with the changed appearance , it first shows the default appearance then after sometime only the changed appearance is shown

NB : This only happens in android . I am using react-native-readium@1.0.4

please have a look into this 
Thanks

**Comment by jspizziri** [comment]
@amalStorilabs thanks for the response. No worries on the delay, opening this back up. A few follow up questions:

1. Are you able to reproduce this issue in the `example` app in this repo?
2. Have you tried upgrading to the latest RC to see if there are any improvements?
